
import com.mysql.cj.xdevapi.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Devika shetty
 */
public class billpage extends javax.swing.JFrame {

    /**
     * Creates new form billpage
     */
    public billpage() {
        initComponents();
//        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        bfcost = new javax.swing.JTextField();
        bcost = new javax.swing.JTextField();
        bccost = new javax.swing.JTextField();
        btcost = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/WhatsApp Image 2023-01-16 at 12.45.59 PM.jpeg"))); // NOI18N
        jLabel6.setText("jLabel6");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/WhatsApp Image 2023-01-16 at 12.45.59 PM.jpeg"))); // NOI18N
        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BILL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Frame cost");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Lens cost");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Coating Cost");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total  Amount");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        jButton5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton5.setText("Proceed");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 284, -1, 30));

        jButton6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton6.setText("BACK");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        bfcost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bfcostActionPerformed(evt);
            }
        });
        getContentPane().add(bfcost, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 80, -1));
        getContentPane().add(bcost, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 80, -1));

        bccost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bccostActionPerformed(evt);
            }
        });
        getContentPane().add(bccost, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 80, -1));

        btcost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcostActionPerformed(evt);
            }
        });
        getContentPane().add(btcost, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 90, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/WhatsApp Image 2023-01-16 at 12.45.59 PM.jpeg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new lenspage().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
          try {
            // TODO add your handling code here:
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/specs","root","Ran10d@i");
            
            String frame_cost = bfcost.getText();
            System.out.println(frame_cost);
            String lens_cost =bcost.getText();
           
            String coatingcost = bccost.getText();
            String totalcost =btcost.getText();
            
            
            String sql="INSERT INTO BILL(fcost,lcost,scost,totalcost) VALUES(?,?,?,?)";
            PreparedStatement  ps =con.prepareStatement(sql);
            
            ps.setString(1, frame_cost);
            ps.setString(2, lens_cost);
            ps.setString(3, coatingcost);
            
            ps.setString(4, totalcost);
            ps.executeUpdate();
            if(2500 < Integer.parseInt(btcost.getText())){
                JOptionPane.showMessageDialog(rootPane, "You got 10% discount");
            }
            
//           String sql1 ="select totalcost from bill where totalcost='"+btcost+"'";
//          
//            PreparedStatement st= con.prepareStatement(sql1);
//           ResultSet rs= (ResultSet) st.executeQuery();
//            rs.next();
//            
//           JOptionPane.showConfirmDialog(this, rs.getString(1)+"is the total amount");
            
            
            
           
            
            
            
            
            
           
            
            
            
            
        } catch(SQLException e){
            e.printStackTrace();
           } catch (ClassNotFoundException ex) {
                JOptionPane.showInputDialog(this,ex);
            Logger.getLogger(billpage.class.getName()).log(Level.SEVERE, null, ex);
        }
          
          
        
        
        
        
        
        
         Warrantypage wg=new Warrantypage();
        wg.show();
        dispose();

    }//GEN-LAST:event_jButton5ActionPerformed

    private void bfcostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bfcostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bfcostActionPerformed

    private void bccostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bccostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bccostActionPerformed

    private void btcostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btcostActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(billpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(billpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(billpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(billpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new billpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField bccost;
    public static javax.swing.JTextField bcost;
    public static javax.swing.JTextField bfcost;
    public static javax.swing.JTextField btcost;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
