/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Devika shetty
 */
public class lenspage extends javax.swing.JFrame {

    /**
     * Creates new form lenspage
     */
    public lenspage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        left1 = new javax.swing.JTextField();
        right1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        type1 = new javax.swing.JComboBox<>();
        jyes1 = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fcost = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        size1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        left1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        left1.setText("LEFT");
        left1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                left1ActionPerformed(evt);
            }
        });
        getContentPane().add(left1, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 175, -1, -1));

        right1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        right1.setText("RIGHT");
        getContentPane().add(right1, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 175, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("lens power");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 175, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Lens Type");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 225, 80, -1));

        type1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Antiglass", "blue cut computer lens" }));
        type1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                type1ActionPerformed(evt);
            }
        });
        getContentPane().add(type1, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 225, -1, 20));

        jyes1.setSelected(true);
        jyes1.setText("YES");
        jyes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jyes1ActionPerformed(evt);
            }
        });
        getContentPane().add(jyes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Scratch resistant coating");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 275, 180, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("frame cost: ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 325, 70, -1));

        fcost.setText("100");
        getContentPane().add(fcost, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 325, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Size");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 355, -1, -1));

        size1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Small", "Medium", "Large" }));
        getContentPane().add(size1, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 355, -1, -1));

        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setText("Proceed");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 375, -1, -1));

        jButton3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 75, -1, -1));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 615, 0));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/WhatsApp Image 2023-01-16 at 12.45.59 PM.jpeg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 620, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void type1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_type1ActionPerformed

    private void jyes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jyes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jyes1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/specs","root","Ran10d@i");
String fcoste = fcost.getText();
            String lleft = left1.getText();
            String rright = right1.getText();
            String size =(String) size1.getSelectedItem();
            String type =(String) type1.getSelectedItem();
            boolean choice = jyes1.isSelected();
            String rc = "";
            if(choice == true){
                rc = "YES";
            }else{
                rc = "NO";
            }

            String sql="INSERT INTO LENS(lleft,lright,ltype,lcoating ,lsize) VALUES(?,?,?,?,?)";
            PreparedStatement  ps =con.prepareStatement(sql);

            ps.setString(1, lleft);
            ps.setString(2, rright);
            ps.setString(3, type);
            ps.setString(4, rc);
            ps.setString(5, size);

            ps.executeUpdate();
            
             JOptionPane.showMessageDialog(rootPane, "Success");

           int fnum=Integer.parseInt(fcoste);  

 int amount=fnum +600;
            billpage bg=new billpage();
            bg.bfcost.setText(fcoste);
                
             bg.bcost.setText("600");
             if(choice==true){
                 bg.bccost.setText("350"); 
                   amount =   amount + 350; 
             }else{
                bg.bccost.setText("0"); 
                 
             }
            
            
             
             
             
               bg.btcost.setText("" + amount);
            bg.show();
            dispose();

        } catch (Exception ex) {
            ex.printStackTrace();
            // Logger.getLogger(newaccount.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new framepage().setVisible(true);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void left1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_left1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_left1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lenspage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lenspage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lenspage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lenspage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lenspage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel fcost;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JToggleButton jyes1;
    private javax.swing.JTextField left1;
    private javax.swing.JTextField right1;
    private javax.swing.JComboBox<String> size1;
    private javax.swing.JComboBox<String> type1;
    // End of variables declaration//GEN-END:variables
}
